### comment on post 
post http://localhost:5800/comment/commentOnPost
Content-Type: application/json

{
    "userID": "9595ba2e-b289-49c8-a0de-291aa56fb501",
    "postID": "cfbe1627-7ab1-46f7-a1d0-7817a42bd6d4" ,
    "content": "we are both in the 10%",
    "userName": "mike"
}

### get all comments on post
get http://localhost:5800/comment/getPostComments/11c2089d-50e9-4ebc-be77-a6aba4776a9a
Content-Type: application/json



### comment on comment
post http://localhost:5800/comment/commentOnComment
Content-Type: application/json

{
    "userID": "a5c1dee3-8c3a-4b80-abab-5389e8ad5455",
    "postID": "cfbe1627-7ab1-46f7-a1d0-7817a42bd6d4" ,
    "parentCommentID": "ca0b9f66-cdc8-4cf0-9e2d-487941b72963" ,
    "content": "go home",
    "userName": "dogo"
}

### get all comments on comment
get http://localhost:5800/comment/getCommentsOnComment/6282818c-4d6f-4d2a-a025-d56b6c13464d
Content-Type: application/json


### update comment
put http://localhost:5800/comment/updateComment
Content-Type: application/json

{
    "commentID": "90e9836d-4c0d-47e4-949d-22594cec7eb3",
    "updatedContent": "no i changed my mind sorry",
    "userID": "a5c1dee3-8c3a-4b80-abab-5389e8ad5455"
}

### delete comment
delete http://localhost:5800/comment/deleteComment
Content-Type: application/json

{
    "commentID": "34440171-368f-4a54-a336-d8828537090f",
    "userID": "30b8726a-f623-4920-a0da-c77d183bbdca"
}