
### add follow
post http://localhost:5800/follow/addFollow
Content-Type: application/json

{
    "followerID": "30b8726a-f623-4920-a0da-c77d183bbdca",
    "followeeID": "4d087c21-1cc8-48cc-b792-7045b93090bb" 
}

### get followers
get  http://localhost:5800/follow/getFollowers
Content-Type: application/json

{
    "userID": "93c38333-1f1c-45ea-b30c-f0875af6bb89"
    
}
### get followers
GET http://localhost:5800/follow/getFollowers?userID=93c38333-1f1c-45ea-b30c-f0875af6bb89
Content-Type: application/json


### get following
get  http://localhost:5800/follow/getFollowing
Content-Type: application/json

{
    "userID": "a5c1dee3-8c3a-4b80-abab-5389e8ad5455"
    
}

### unfollow user
post http://localhost:5800/follow/unfollow
Content-Type: application/json

{
    "followerID": "a5c1dee3-8c3a-4b80-abab-5389e8ad5455",
    "followeeID": "93c38333-1f1c-45ea-b30c-f0875af6bb89" 
}
