### create post
post http://localhost:5800/post/createPost
Content-Type: application/json

{
    "userID": "30b8726a-f623-4920-a0da-c77d183bbdca",
    "postPic": "nice pics",
    "content": "good morning Africa"
}

### get user posts
get http://localhost:5800/post/getUserPosts
Content-Type: application/json

{
    "userID": "30b8726a-f623-4920-a0da-c77d183bbdca"
}

### get all posts
get http://localhost:5800/post/


### delete post
delete http://localhost:5800/post/deletePost
Content-Type: application/json

{
    "postID": "7a95ac71-9e50-4bdc-a384-d0bd7f467e17"
}