### register user
post  http://localhost:5800/user/register
Content-Type: application/json

{

    "userName": "Daniel",
    "email": "gamemy177@gmail.com",
    "password": "Mike123.100#"

}

### login user
post  http://localhost:5800/user/login
Content-Type: application/json

{

    "userName": "Daniel",
    "password": "Mike123.100#"
}

### get get_email_userName
get  http://localhost:5800/user/get_email_userName

### get all users
get  http://localhost:5800/user/

### follow user
post  http://localhost:5800/user/followUser
Content-Type: application/json

{

    "userID": "93c38333-1f1c-45ea-b30c-f0875af6bb89",
    "userFollowedID": "9595ba2e-b289-49c8-a0de-291aa56fb501"
}

### update user profile
put  http://localhost:5800/user/updateProfile
Content-Type: application/json

{

    "userName": "Daniell",
    "email": "gamemy177@gmail.com",
    "password": "Mike123.1000#"

}


### request password reset
post http://localhost:5800/user/requestPasswordReset
Content-Type: application/json

{
    
    "email":"gamemy177@gmail.com"
}



### update password

post http://localhost:5800/user/resetPassword
Content-Type: application/json

{
    
    "email":"mikevenum9@gmail.com",
    "newPassword":"Mike123.100%",
    "token":"bkq8z8h3hd6v092fyp4mzc"
   
}

