### register user
post  http://localhost:5800/user/register
Content-Type: application/json

{

    "userName": "mike",
    "email": "mikevenum9@gmail.com",
    "password": "Mike123.100#"

    
}

### login user
post  http://localhost:5800/user/login
Content-Type: application/json

{

    "userName": "mike",
    "password": "Mike123.100#"
}

### get get_email_userName
get  http://localhost:5800/user/get_email_userName

### get all users
get  http://localhost:5800/user/

### follow user
post  http://localhost:5800/user/followUser
Content-Type: application/json

{

    "userID": "34ad6d54-3fc0-4209-9994-f5c0c5ba089e",
    "userFollowedID": "9738c159-02ea-470d-a63d-6f791041775a"
}

### update user profile
put  http://localhost:5800/user/updateProfile
Content-Type: application/json

{

    "userName": "Cylvonne",
    "email": "cylvonnen@gmail.com",
    "password": "Mike123.1000#"

}

### uplaod user profile image
post  http://localhost:5800/user/uploadProfilePic
Content-Type: multipart/form-data

{

    "profilePic": "../backend/public/uploads/talky3.jpeg",
    "userID": "9738c159-02ea-470d-a63d-6f791041775a"

}


### request password reset
post http://localhost:5800/user/requestPasswordReset
Content-Type: application/json

{
    
    "email":"mikevenum9@gmail.com"
}



### update password

post http://localhost:5800/user/resetPassword
Content-Type: application/json

{
    
    "email":"mikevenum9@gmail.com",
    "newPassword":"Mike123.100%",
    "token":"bkq8z8h3hd6v092fyp4mzc"
   
}

