### register user
post  http://localhost:5800/user/register
Content-Type: application/json

{

    "userName": "test",
    "email": "jame@gmail.com",
    "password": "123456"
}

### login user
post  http://localhost:5800/user/login
Content-Type: application/json

{

    "userName": "test",
    "password": "123456"
}

### get get_email_userName
get  http://localhost:5800/user/get_email_userName

### get all users
get  http://localhost:5800/user/

### follow user
post  http://localhost:5800/user/followUser
Content-Type: application/json

{

    "userID": "34ad6d54-3fc0-4209-9994-f5c0c5ba089e",
    "userFollowedID": "9738c159-02ea-470d-a63d-6f791041775a"
}
